feat/ci-linting
Studio-Yandex-Practicum/bmc_companion_bot pull request #1
Opened 2022-12-16 09:05 UTC by alkh0304

Добавлен workflow файл, осуществляющий проверку линтерами flake8 и black при pull реквестах

2022-12-19 07:51 UTC, xczdenis requested changes
Все супер!) Есть предложение, но оно опциональное - сделать так, чтобы джобы запускались на разных версиях питона (3.10, 3.11). В этом тебе поможет matrix.

И еще важное замечание - старайся придерживаться [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) при написании комментариев к комиту. На этом коммите лучше написать ci. У нас это написано в ридми

2022-12-19 07:51 UTC, xczdenis commented on .github/workflows/lint.yml
> +      - uses: actions/checkout@v2
Есть более свежая версия
```suggestion
      - uses: actions/checkout@v3
```

Давай сформируем общее правило оформления для шагов такое: каждый шаг должен содержать name. Так мы сможем более гибко управлять своими шагами (сможем задавать наши имена, а не стандартные). Тогда каждый шаг нужно переписать в таком ключе
```suggestion
-   name: Checkout code
    uses: actions/checkout@v3
```

2022-12-19 12:17 UTC, alkh0304 commented on .github/workflows/lint.yml
> +      - uses: actions/checkout@v2
Спасибо за подробные комментарии, с правками согласен, изменения внес :)

2022-12-20 09:16 UTC, xczdenis approved these changes
LGTM!

2022-12-20 10:19 UTC, merged