feat: добавлена модель user_time_slots
Studio-Yandex-Practicum/bmc_companion_bot pull request #40
Opened 2023-01-17 18:12 UTC by thalq

- Все эндпоинты работают. Возможно нужна дополнительная вариация времени: чтобы время окончания слота не было меньше времени начала. Если что, добавлю чуть позже.

2023-01-18 13:02 UTC, xczdenis requested changes
В целом не плохо. Только бизнес логику из роутов нужно убрать. См. коммент

2023-01-18 13:02 UTC, xczdenis commented on webapi/src/app/models/tests.py
> +class UserTimeSlot(BaseModel):
В этой модели еще должна быть ссылка на юзера потому что слоты добавляются для конкретного юзера. Нужно добавить user_id. Забыл указать это в задаче((

2023-01-18 13:02 UTC, xczdenis commented on webapi/src/app/api/v1/user_time_slot/routers.py
> +        return abort(HTTPStatus.CONFLICT, "Такой временной слот уже существует!")
Вот эти все методы - get_object_by_id, check_object и все что ниже - это слой бизнес логики. Он не должен иметь отношения к роутам. Роуты - это представления (они же вьюхи). Задача вьюхи - принять запрос, отвалидировать параметры и запустить на выполнение какуюто функцию. Так вот эта какая то функция - она должна быть реализована в отдельном сервисе (это может быть класс). Этот сервис будет являться бизнес логикой приложения. Таким образом бизнес логика не будет пересекаться с вьюхами.

Посмотри как сделаны юзеры. У нас по моему уже есть сервис по работе с юзерами.

2023-01-19 14:33 UTC, thalq commented on webapi/src/app/api/v1/user_time_slot/routers.py
> +        return abort(HTTPStatus.CONFLICT, "Такой временной слот уже существует!")
Готово!

2023-01-19 14:33 UTC, thalq commented on webapi/src/app/models/tests.py
> +class UserTimeSlot(BaseModel):
Я, кстати, обсуждала это с Лешей и удивлялась, а как же без юзера мы тут )

2023-01-19 15:08 UTC, xczdenis approved these changes
Nice!

2023-01-19 15:23 UTC, merged