Feat/admin menu protect
Studio-Yandex-Practicum/bmc_companion_bot pull request #47
Opened 2023-01-20 13:26 UTC by SergoSolo

- Добавлена защита админки от обычных юзеров

2023-01-20 13:45 UTC, xczdenis requested changes
Отлично! Только парочка замечаний

2023-01-20 13:45 UTC, xczdenis commented on bot/src/handlers/admin/root_handlers.py
> +        await back_to_start_menu(update, context)
мне кажется ветка else должна возвращать какое-то состояние. Здесь возможно будет ошибка. Попробуй потестить поглубже под обычным юзером. Старт - затем админка - затем снова админка - снова админка - потом будут ли работать остальные кнопки? Возможно что после того как выплюнется это сообщение, остальные кнопки перестанут работать. Чтобы это проверить, можешь пока что временно написать обработчики для остальных кнопок, потом их грохнуть.

2023-01-20 13:45 UTC, xczdenis commented on bot/src/request/clients.py
> +        ][0]
здесь может быть пустой список, тогда выскочит ошибка

2023-01-20 13:45 UTC, xczdenis commented on bot/src/request/clients.py
> +        if UserRole(user_role_id).name != "USER":
1. если сравниваешь со строками, то всегда используй преобразование к регистру либо lower() либо upper().
2. Подобные строки лучше не хардкодить, лучше вынести в настройки через env
3. Мне кажется проверять на не равно - не лучшая идея. Что если мы захотим ввести роль "ОбычныйПользователь" - тогда вернется true. Лучше проверять явно на равенство либо админ либо рут.

2023-01-21 14:37 UTC, SergoSolo commented on bot/src/handlers/admin/root_handlers.py
> +        await back_to_start_menu(update, context)
Ну вроде проверил. Для кнопки "пройти тест" написал ConversationHandler с 2 кнопками, вернуться в меню или просто вывести текст.  Обычным юзером писал команду /admin, выводилось сообщение "доступа нет" и перекидывало в главное меню. Вы главном меню кнопки функционировали, возврат в главное меню и вывод текста срабатывало без ошибок. Все это многократно повторял. И по идее функция `back_to_start_menu` делает возврат состояния `return BotState.END`

2023-01-23 14:15 UTC, xczdenis approved these changes
LGTM!

2023-01-23 14:17 UTC, merged