Docs/readme summary
Studio-Yandex-Practicum/bmc_companion_bot pull request #6
Opened 2022-12-18 18:30 UTC by opzhai

Добавлены оглавление и дропдауны в READme

2022-12-19 07:22 UTC, xczdenis requested changes
Все круто, единственное что не увидел - это [ссылка на Оглавление](https://github.com/GnuriaN/format-README#%D0%9E%D0%B3%D0%BB%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5) в конце каждого раздела

И еще важное замечание - старайся придерживаться [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) при написании комментариев к комиту. На этом коммите лучше написать docs. У нас это написано в ридми

2022-12-19 07:22 UTC, xczdenis commented on README.md
> +[Создание среды разработки](#Создание-сред-разработки) <br>
здесь опечатка в идентификаторе (сред вместо среды)

2022-12-19 13:38 UTC, opzhai commented on README.md
> +[Создание среды разработки](#Создание-сред-разработки) <br>
Ссылки на оглавления мне показались излишними, сейчас добавил+внес остальные правки

2022-12-20 09:12 UTC, xczdenis approved these changes

2022-12-20 15:26 UTC, merged