Feat/implement notifications via celery
Studio-Yandex-Practicum/bmc_companion_bot pull request #64
Opened 2023-02-08 06:12 UTC by bmu0

2023-02-09 13:25 UTC, xczdenis requested changes
Ок. Небольшие рекомендации см. в комментах. И не забудь дополнить env.example всеми новыми настройками, которые ты используешь

2023-02-09 13:25 UTC, xczdenis commented on adminpanel/src/config/settings/components/base.py
> +CELERY_BROKER_URL = "redis://127.0.0.1:6379"
такие штуки нельзя хардкодить. Их нужно задавать через переменные окружения

2023-02-09 17:20 UTC, bmu0 commented on adminpanel/src/config/settings/components/base.py
> +CELERY_BROKER_URL = "redis://127.0.0.1:6379"
сделано

2023-02-13 14:41 UTC, xczdenis approved these changes
LGTM!

2023-02-13 15:06 UTC, merged