Реализовать ограничение на запись для пользователя
Studio-Yandex-Practicum/bmc_companion_bot pull request #72
Opened 2023-02-25 13:51 UTC by Hastred45

В рамках задачи в `TimeSlotViewSet` добавлен фильтр только по свободным таймслотам через query-параметр `is_free`.

В модель `Meeting` добавлена связь `OneToOneField` с моделью `TimeSlot`, чтобы через нее находить свободные таймслоты.

В методе `get_actual_timeslots` теперь есть необязательный параметр `is_free: str = "False"` 

Чтобы запретить пользователю записываться повторно, нам нужно проверить его актуальные записи.
Для этого я добавил в `MeetingViewSet` метод `get_queryset`, который при `is_active == "True"` фильтрует список записей пользователя и возвращает только будущие. А так как сейчас нельзя записаться больше одного раза, то мы получаем одну запись или ничего. Если данная запись есть, пишем ее данные и возвращаем в главное меню.

Хотел убарть код проверки записи в файл utils.py, но появилась проблема с импортами, которую я не смог решить. Из-за вот этой строчки `ps = user_service_v1.get_user(id=meeting_obj.psychologist)`. Не получилось в utils.py импортировать `user_service_v1`

Дополнительно поправил ошибку вывода информации при повторной записи. 
Было :
<img width="498" alt="Снимок экрана 2023-02-25 в 17 55 58" src="https://user-images.githubusercontent.com/98474842/221360334-fec81536-496c-4cd0-ba37-08e8dd86f82e.png">

Стало:
<img width="286" alt="Снимок экрана 2023-02-25 в 18 00 17" src="https://user-images.githubusercontent.com/98474842/221360352-760bd437-c436-43af-a53c-f3372179f847.png">

2023-02-27 13:34 UTC, bmu0 requested changes
Неплохо, но есть что поправить.

2023-02-27 13:34 UTC, bmu0 commented on bot/src/handlers/meeting/meeting_first.py
> +            return BotState.MENU_START_SELECTING_LEVEL
![ботупал](https://user-images.githubusercontent.com/96753994/221569422-a056ba09-7214-4e78-ad0e-590d52a4319d.PNG)

при наличии записи бот выпадает из диалога, надо подумать куда его вернуть без ошибок

2023-02-27 13:34 UTC, bmu0 commented on docker-compose.yml
> +    webapi:
Сервис webapi неактуален и использоваться в проекте не будет

2023-02-27 13:34 UTC, bmu0 commented on bot/src/handlers/meeting/meeting_repeat.py
> +            text_was = f"\n\n{'Вы уже были у этих психологов:'}"
Чтобы не было пустого пространства при отсутствии блока text_wasnt, можно убрать "\n\n" из text_was и добавить в конец text_wasnt

2023-02-27 13:34 UTC, bmu0 commented on bot/src/handlers/meeting/meeting_repeat.py
>                  meeting_format=10
Небольшая идея для рефактора: 10 и 20 - совсем неочевидное обозначение формата.
В модели Meeting есть 
MEETING_FORMAT_ONLINE = 10
MEETING_FORMAT_OFFLINE = 20
Лучше будет импортировать модель и использовать эти читаемые атрибуты, которые ничего не сломают например при смене этих значений в модели.

2023-02-27 15:41 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_repeat.py
>                  meeting_format=10
В readme указано следующее:

> Выполняй импорты из каталогов, вложенных в src. Следи, чтобы твои импорты не начинались с папки src.

А мне получается надо не просто выйти за src, а отправить за моделью из бота в админку. Если я правильно понимаю, то таких импортов в проекте нет. Бот берет все что ему нужно от админки и бд через апи?

2023-02-27 16:16 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_repeat.py
> +            text_was = f"\n\n{'Вы уже были у этих психологов:'}"
Если так сделать, то получится вот такое сообщение:

<img width="485" alt="Снимок экрана 2023-02-27 в 20 44 26" src="https://user-images.githubusercontent.com/98474842/221610372-2d2294d7-e14a-4a27-ad10-a44cc030ddd3.png">

Как мне кажется, тут проблема в том, что психологи у которых клиент еще не был, выводятся раньше. Но это не логично) Лучше раньше ставить тех, у кого клиент уже был, потому что это повторная запись и такой повторный психолог точно должен быть.А из-за того, что может не быть психолога, у которого клиент не был и получается разрыв в тексте. А если бы он в конце, то это не было бы проблемой. Я попробовал разобраться с кодом, который формирует это сообщение и тут странно. По идее он должен все делать правильно:
- сначала проверяет тех у кого был
- потом тех у кого не был
<img width="382" alt="Снимок экрана 2023-02-27 в 21 01 57" src="https://user-images.githubusercontent.com/98474842/221614898-2a200908-c8cd-485a-8857-56e56133f295.png">
Но получается наоборот почему-то

2023-02-27 16:51 UTC, Hastred45 commented on docker-compose.yml
> +    webapi:
Без него у меня не запускался проект
<img width="895" alt="Снимок экрана 2023-02-27 в 21 50 55" src="https://user-images.githubusercontent.com/98474842/221627517-8856a61d-2a33-4d51-bf0d-e6a473105578.png">

2023-02-28 07:41 UTC, bmu0 commented on bot/src/handlers/meeting/meeting_repeat.py
>                  meeting_format=10
да, в бот нельзя импортить из админки. вообще по-хорошему это надо прописать в env и оттуда получать как в боте так и в админке, но пока давай просто оставим как есть

2023-02-28 07:46 UTC, bmu0 commented on docker-compose.yml
> +    webapi:
это я написал просто для информации :) докер пока без него не работает, потому что не переписан под adminpanel

2023-02-28 09:44 UTC, bmu0 commented on bot/src/handlers/meeting/meeting_repeat.py
> +            text_was = f"\n\n{'Вы уже были у этих психологов:'}"
предлагаю переработать формирование этого списка. 
Суть - создаем массив ['Выберите дату и время записи:',]
Если есть у кого были - добавляем в массив '\n
![sdf](https://user-images.githubusercontent.com/96753994/221815049-b02ec772-6480-453e-b070-9b08f24bc4de.PNG)
Вы уже были у этих психологов:'
Далее по одному строки с психологами
Если есть у кого не были - добавляем '\nВы еще не были у этих психологов:'
Далее по одному строки
И в конце делаем '\n'.join(массив)

2023-02-28 21:40 UTC, ADesBiysk commented on bot/src/services/schedule_service.py
> +    ) -> MeetingResponse | list[MeetingResponse]:
Нужно выбрать один из вариантов. Такая аннотация типов выглядит странно.

2023-02-28 21:40 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_repeat.py
> +        user_active_meeting = schedule_service_v1.get_meetings_by_user(
Почему проверка существования пользователя находится ниже? 
Если пользователя не существует, то get_user вернёт None и программа упадёт здесь: user=user.id

2023-02-28 22:10 UTC, Hastred45 commented on bot/src/services/schedule_service.py
> +    ) -> MeetingResponse | list[MeetingResponse]:
Оставил list.

2023-03-01 22:30 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_first.py
> +            return BotState.MENU_START_SELECTING_LEVEL
Проблема была в `map_to_parent={
        BotState.STOPPING: States.TYPING_COMMENT,
        BotState.END: BotState.MENU_START_SELECTING_LEVEL,
    },` я заменил `BotState.MENU_START_SELECTING_LEVEL` на `BotState.END` и теперь после проверки на активную запись, нормально перенаправляет в главное меню. Также поправил возврат в меню после создания новой записи (она тоже не работала).

2023-03-01 22:36 UTC, Hastred45 commented on docker-compose.yml
> +    webapi:
Я закомитил как было до меня

2023-03-01 22:45 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_repeat.py
> +            text_was = f"\n\n{'Вы уже были у этих психологов:'}"
По итогу я сделал комбо из того что было и того что ты предложил. Когда начал делать твой вариант с двумя списками, я понял что мы не можем произвольно их заполнять психологами. Нам нужно чтобы в сообщении они шли в том же порядке, что и в ответе `TimeslotResponse`, потому что потом по номеру в сообщении мы берем таймслот и психолога для создания записи. А если порядок в сообщении будет другой (и нумерация следовательно тоже), то нам просто будет выдавать не те таймслоты

> <img width="350" alt="Снимок экрана 2023-02-28 в 22 42 08" src="https://user-images.githubusercontent.com/98474842/222281967-fe34cf05-d51d-4c35-9a46-fe3322c6d395.png">

И мы не можем сначала рассортировать психологов по спискам, а потом соединить. Я решил проблему в основании. Отсортировал список ответа `TimeslotResponse` по тому был пользователь у психолога или нет. Те у кого не был, идут в конец отсортированного списка (плюс еще сортирует по дате таймслота, чтобы было красиво). И теперь мы можем разделить психологов по спискам был/не был, не боясь нарушить их порядок. А потом все соединяем и отдаем пользователю.

2023-03-01 22:45 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_repeat.py
> +        user_active_meeting = schedule_service_v1.get_meetings_by_user(
Поставил проверку в нужное место

2023-03-01 22:54 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_first.py
> +            return BotState.MENU_START_SELECTING_LEVEL
Еще я обнаружил баг в повторной записи. Она не создается и выдает ошибку:
`TypeError: ScheduleApiService.create_meeting() missing 1 required positional argument: 'comment'`
При создании новой записи пропущено поле `comment`. Я пока не стал туда лезть. Надо определить что с этим делать и может завести отдельную задачу? Потому что тут получается надо добавлять в процесс повторной записи еще и запрос - "О чем бы вы хотели поговорить с психологом?". Или он тут не нужен и можно `comment` какой-то по умолчанию проставить, например `-`.

2023-03-03 07:31 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_first.py
> +        user_active_meeting = schedule_service_v1.get_meetings_by_user(
В данном случае, довольно большой кусок бизнес-логики повторяется в 2 файлах. 
Предлагаю подумать о том, чтобы вынести его в отдельную функцию.
Например, check_and_make_message_for_active_meeting(user_id) -> str | None

2023-03-03 07:31 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_repeat.py
> +                list_ps.append(psycho_name.id)
Я правильно понимаю, что здесь берётся из сущности meeting значение поля psychologist, которое является первичным ключём сущности Profile, запрашиваем всю сущность и потом снова берём её id?
Т.е. получаем то, что уже есть у сущности Meeting.

2023-03-03 07:31 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_repeat.py
>              for index, timeslot in enumerate(timeslots):
У enumirate есть параметр start. Можно задать его равным 1, и не прибавлять к индексу единицу на каждом шаге.

2023-03-03 07:31 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_repeat.py
>                  meeting_format=10
Я бы вынес в константы эти "магические" числа. Пусть они будут захардкодены, но только в одном месте.

2023-03-03 15:00 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_repeat.py
> +                list_ps.append(psycho_name.id)
Да, убрал это. Когда только приступал к задаче, отметил что надо это убрать. Потом забылось) Это до меня было. Теперь просто берем id из meeting

2023-03-03 19:32 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_repeat.py
>                  meeting_format=10
Добавил константы в .env и подгрузил в constants.py бота

2023-03-03 19:36 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_first.py
> +        user_active_meeting = schedule_service_v1.get_meetings_by_user(
Оставил в файлах саму проверку наличия активной встречи. Формирование сообщения убрал в файл handlers_utils.py. У меня не получилось вынести это в utlis.py из-за ошибки импорта `user_service_v1` из `app`. 
`ImportError: cannot import name 'user_service_v1' from partially initialized module 'app' (most likely due to a circular import)`

2023-03-03 19:52 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_repeat.py
> +                list_ps.append(psycho_name.id)
Поменял list на set. Заметил в ходе тестирования, что у нас туда помещает id одного психолога несколько раз, а нам это вообще не нужно + по set быстрее поиск, когда определяем был или не был у психолога.

2023-03-03 19:52 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_repeat.py
>              for index, timeslot in enumerate(timeslots):
Добавил

2023-03-06 13:17 UTC, bmu0 commented on bot/src/handlers/meeting/meeting_first.py
> +            return BotState.MENU_START_SELECTING_LEVEL
Давай по умолчанию поставим "повторная запись". Надо чтобы работало, а если будет не так - заказчик сообщит.

2023-03-06 21:51 UTC, ADesBiysk commented on .env.template
> +MEETING_FORMAT_ONLINE=10
Эти константы не связаны с деплоем и их не нужно часто изменять. Поэтому, нужно убрать отсюда и просто захардкодить в константах так https://github.com/Studio-Yandex-Practicum/bmc_companion_bot/blob/fb7a762adf48002576e71acdb9edbf6fa8b65b74/bot/src/core/constants.py#L59

2023-03-06 21:51 UTC, ADesBiysk commented on bot/src/handlers/handlers_utils.py
> +def make_message_for_active_meeting(user_active_meeting) -> str:
: list[MeetingResponse]

2023-03-06 21:51 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_repeat.py
> +                    elif ts_psycho not in psycho_set:
Здесь не понял. Если психолог есть в списке, то зачем проверять что его там нет. Код не эквивалентен этому? 
```
if ts_psycho in psycho_set:
   ...
else:
   ...
```

2023-03-06 21:51 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_repeat.py
> +                    elif ts_psycho not in psycho_set:
И конфликт нужно устранить.

2023-03-06 21:53 UTC, ADesBiysk approved these changes
Небольшие замечания.

2023-03-07 11:08 UTC, Hastred45 commented on .env.template
> +MEETING_FORMAT_ONLINE=10
Поправил!

2023-03-07 11:08 UTC, Hastred45 commented on bot/src/handlers/handlers_utils.py
> +def make_message_for_active_meeting(user_active_meeting) -> str:
Поправил!

2023-03-07 11:08 UTC, Hastred45 commented on bot/src/handlers/meeting/meeting_repeat.py
> +                    elif ts_psycho not in psycho_set:
Поправил!

2023-03-07 11:37 UTC, bmu0 approved these changes

2023-03-07 11:38 UTC, merged