Feat/handler reschedule meeting
Studio-Yandex-Practicum/bmc_companion_bot pull request #74
Opened 2023-02-28 10:02 UTC by Hlompy

Исправил ошибку с JSON, функционал работает.

2023-03-01 14:02 UTC, bmu0 requested changes
Работа с базой проходит нормально, но надо бы поправить ошибки в боте.

2023-03-01 14:02 UTC, bmu0 commented on bot/src/services/schedule_service.py
> +    def delete_meeting(self, meeting_id) -> MeetingResponse:
![авфы](https://user-images.githubusercontent.com/96753994/222161738-f43f7ea3-5163-4e56-bd0a-27753b4d5ede.PNG)

при удалении падает с ошибкой очень похожей на ошибку в апдейте которую недавно обсуждали

2023-03-01 14:02 UTC, bmu0 commented on bot/src/services/schedule_service.py
> +    def update_meeting(
![пыук](https://user-images.githubusercontent.com/96753994/222162157-382fff42-511f-4081-bc8e-b0f3d7a50f9f.PNG)

тут какая-то проблема со списком, если таймслотов 2

2023-03-01 21:21 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_cancel.py
> +        text += f"{meeting.date_start}"
```suggestion
    text_parts = ["Выберите запись для отмены:\n"]
    for index, meeting in enumerate(meetings, start=1):
        psychologist_profile = user_service_v1.get_user(id=meeting.psychologist)
        text_parts.append(f"\n{index}. {psychologist_profile.first_name} {psychologist_profile.last_name} ")
        text_parts.append(f"{meeting.date_start}")
```

2023-03-01 21:21 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_cancel.py
> +        text = "У вас нет записи"
```suggestion
        text_parts = ["У вас нет записи"]
```

2023-03-01 21:21 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_cancel.py
> +    await update.message.reply_text(text=text, reply_markup=keyboard)
```suggestion
    await update.message.reply_text(text="".join(text_parts), reply_markup=keyboard)
```

2023-03-01 21:21 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_cancel.py
> +    meeting_number = int(update.message.text)
Если пользователь случайно пришлёт не только число, но и букву, то всё сломается. Исключение не обрабатывается.

2023-03-01 21:21 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_cancel.py
> +    meeting_id = meetings[meeting_number - 1].id
Нужна проверка диапазона. Если записей 2, а пользователь напишет 3?

2023-03-01 21:21 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_repeat.py
> +                    if ts_ps not in list_ps:
Странный кусок кода. Понимаю что не твой, но раз уж его тронул, то стоит хоть немного лучше сделать. А так здесь простор для рефакторинга.
```
                    if ts_ps in list_ps:
                        if text_was not in text:
                            text += text_was
                    else:
                        if text_wasnt not in text:
                            text += text_wasnt
                    text += add_ps
```

2023-03-01 21:21 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_reschedule.py
> +            number_of_timeslot = int(update.message.text)
Большой кусок кода повторяется в 3 файлах. :(
Теперь недостаток такого подхода: 
1. Здесь не проверки, что пользователь ввёл число только число. 
2. Нет проверки диапазона значений при выборке из списка timeslots.
И эти изменения, по-хорошему, надо сделать в 3 файлах.

2023-03-01 21:21 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_reschedule.py
> +        text = ""
Мне кажется, более универсальным и быстрым вариантом составления итогового сообщения, это собрать в список отдельные фразы, а перед отправкой — соединить его через join.

2023-03-01 21:21 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_reschedule.py
> +                meeting_format=10
"Магические" числа предлагаю прописать в константах. Импортировать их из моделей админки нельзя, но так хотя бы они прописаны в одном месте, а не разбросаны по всем файлам.

2023-03-02 02:24 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_repeat.py
> +                    if ts_ps not in list_ps:
Это будет исправлено в соседней ветке.

2023-03-05 19:34 UTC, Hlompy commented on bot/src/services/schedule_service.py
> +    def delete_meeting(self, meeting_id) -> MeetingResponse:
Осталась только эта ошибка. Она происходит на 51 строчке, так как при удалении пользователь не получает сообщение о том, что запись удалена(сообщение содержится на следующей 52 строчке). Добавил слэш в функцию delete_meeting(без слэша не работало удаление), но ошибка не ушла.
![Снимок экрана от 2023-03-05 23-27-48](https://user-images.githubusercontent.com/91170890/222981616-4021d8d9-d9b6-426d-9522-7fb60d4583bb.png)

2023-03-06 21:33 UTC, ADesBiysk approved these changes
Только очень мелкие замечания.

2023-03-06 21:33 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_cancel.py
> +    chat_data = update.message.chat
Здесь получается объект Chat, но далее используется только chat_id. Лучше сразу забирать chat_id из update.

2023-03-06 21:33 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_cancel.py
> +    if str(meeting_number) == "Главное меню":
Зачем явное преобразование в строку? 

> Instance attribute text of telegram._message.Message text: str | None = text

2023-03-06 21:33 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_reschedule.py
> +        chat_data = update.message.chat
Здесь также. Без временной переменной понятнее.

2023-03-06 21:33 UTC, ADesBiysk commented on bot/src/handlers/meeting/meeting_reschedule.py
> +        await update.message.reply_text(text="".join(text_parts), reply_markup=keyboard)
Если все условия не выполнились, то text_parts будет не определён.

2023-03-07 11:41 UTC, bmu0 approved these changes

2023-03-07 20:06 UTC, merged