Feat/feedback function added
Studio-Yandex-Practicum/bmc_companion_bot pull request #77
Opened 2023-03-05 18:00 UTC by ravimb06

2023-03-06 11:26 UTC, bmu0 requested changes
Отлично! Есть пара поправок

2023-03-06 11:26 UTC, bmu0 commented on bot/src/handlers/meeting/feedback.py
> +            return BotState.STOPPING
STOPPING выдает ошибку, давай возвращать END для выхода из диалога

2023-03-06 11:26 UTC, bmu0 commented on bot/src/handlers/meeting/feedback.py
> +            return BotState.STOPPING
То же самое, поменяй на END

2023-03-06 11:26 UTC, bmu0 commented on bot/src/handlers/meeting/feedback.py
> +            for index, meeting in enumerate(meetings):
Тут выдается список консультаций, но даже тех которые еще не прошли, то есть есть возможность оставить отзыв до консультации. Надо бы отфильровать по времени только прошедшие

2023-03-07 06:08 UTC, ADesBiysk commented on bot/src/handlers/meeting/feedback.py
> +        if user is None:
Если пользователя нет, то предыдущая строчка вызовет исключение.

2023-03-07 06:08 UTC, ADesBiysk commented on bot/src/handlers/meeting/feedback.py
> +            text = "У вас еще небыло консультаций."
не было

2023-03-07 06:08 UTC, ADesBiysk commented on bot/src/handlers/meeting/feedback.py
> +                psichologist = user_service_v1.get_user(id=meeting.psychologist)
psYchologist

2023-03-07 06:08 UTC, ADesBiysk commented on bot/src/handlers/meeting/feedback.py
> +            number_of_meeting = int(update.message.text)
Если пользователь отправит "1.", то будет вызвано исключение.

2023-03-07 06:08 UTC, ADesBiysk commented on bot/src/handlers/meeting/feedback.py
> +            meeting = meetings[number_of_meeting - 1] if meetings else {}
То что meetings не пустой проверили в начале функции, а то что пользователь выслал номер не выходящий за диапазон - нет.

2023-03-07 06:08 UTC, ADesBiysk commented on bot/src/services/schedule_service.py
> +    def get_feedback_by_user_and_meeting(
Сомневаюсь, что нужна будет возможность оставить 2 разных отзыва для одной консультации.
Поэтому надо сразу возвращать один объект или None, а не список.

2023-03-07 06:08 UTC, ADesBiysk commented on bot/src/handlers/meeting/feedback.py
> +            score = update.message.text
Стоит проверить, что пользователь ввёл число в нужном диапазоне. Если ошибся, то нужно попросить ввести корректное число.

2023-03-07 06:08 UTC, ADesBiysk commented on bot/src/handlers/meeting/feedback.py
> +            if user.id == meeting.user:
Если это условие не выполнится, то это значит, что пользователь смог оставить отзыв о чужой консультации?

2023-03-08 16:54 UTC, ravimb06 commented on bot/src/handlers/meeting/feedback.py
> +            if user.id == meeting.user:
Это условие на проверку того что отзыв оставил пациент, а не психолог. И если отзыв оставил психолог то сообщение пациенту не отправляем. Если я правильно понял задачу

2023-03-08 18:06 UTC, bmu0 approved these changes

2023-03-08 18:06 UTC, merged