feat: Добавлен контейнер для adminpanel
Studio-Yandex-Practicum/bmc_companion_bot pull request #80
Opened 2023-03-09 12:10 UTC by Hastred45

Сделал на основе докер файла и скриптов от webapi. Проверил, должно работать нормально

2023-03-09 13:29 UTC, bmu0 requested changes

2023-03-09 13:29 UTC, bmu0 commented on docker/adminpanel/scripts/start.sh
> +python -m flask db upgrade
Почему тут фласк? тут должны быть миграции и запуск админки, желательно сразу через gunicorn

2023-03-09 18:17 UTC, ADesBiysk commented on docker-compose.yml
> +            - POSTGRES_PORT=5432
Стандартный порт надо поменять на любой другой. Пусть будет, 6100. Как только БД будет видна наружу её будут постоянно сканировать, что создаст лишнюю нагрузку на сервер.

2023-03-11 21:02 UTC, ADesBiysk commented on docker/adminpanel/Dockerfile
> +COPY ./pyproject.toml ./poetry.lock /
Эти файлы надо почистить. Сейчас там есть Flask и куча библиотек для него. Они уже не будут использоваться.

2023-03-12 07:44 UTC, ADesBiysk commented on docker/adminpanel/Dockerfile
> +        build-essential=12.9 \
Это действительно нужно?

2023-03-12 07:44 UTC, ADesBiysk commented on docker/adminpanel/Dockerfile
> +COPY ./pyproject.toml ./poetry.lock /
Причём, поскольку у нас 2 контейнера и зависимости не пересекаются, то нужно их разделить на 2 группы. Одни для бота, другие для админки.

2023-04-02 11:07 UTC, closed without merging